pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        // Build and deploy backend application
        sh 'echo "Building backend application..."'
        sh 'javac multi-stage-multi-agent/HelloWorld.java'
        sh 'java multi-stage-multi-agent/HelloWorld'
        sh 'echo "Backend deployed!"'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        // Build and deploy frontend application
        sh 'echo "Building frontend application..."'
        // Assuming the index.js file is in the current directory
        sh 'node multi-stage-multi-agent/index.js'
        sh 'echo "Frontend deployed!"'
      }
    }
  }
}

